### ISSUE TITLE
Movie Poster Feature - More documentation please

### ISSUE THREAD

**Issue by bdgarmon** [sahara101/Movie-Roulette#46]
When multiple people are watching Plex the Movie Poster feature displays one of the movies being played but seems to ignore the other streams. How does it determine which poster to display? 

For multiple streams will it shuffle between the different streams? 

Are there different URL's available to link the movie poster being displayed to a specific user? For example /poster/userA /poster/userb?

I've also noticed that if the streams are coming in remotely, the poster is displayed properly, but for Plex content being played on the same LAN as the Plex Server using the Apple TV plex app, the movie poster remains at the static red empty theater logo. I found it odd that Apple TV app works properly when the Apple TV is remote, but not local.

**Comment by sahara101** [comment]
I just noticed a bug which came somewhere between my test and dev/prod version. Normally, it should only show for authorized users. But I just checked and I get a poster even if no user is authorized. 

Posters should update according to last active authorized stream. I could make a better distinction here. Right now if userA starts a movie you would see movieA poster  but if userB starts a movie right afterwards you will instantly get the movieB poster. 


As for the LAN, it should not behave like that. As long as a user is authorized it should update the poster (which right now it does regardless). Do you see any docker logs?

Sorry for the error!

**Comment by sahara101** [comment]
There also seems to be a bug in the auth users logic so I need to check that.

**Comment by sahara101** [comment]
The bug is now fixed and I will release it in the next few days. 
What is your use case? I ask so that I know how to handle multiple streams best. 

Last Active
Rotation
Priority
Smart Selection, for example by priority + progress + time passed, etc
Or other?

**Comment by sahara101** [comment]
Doing now last active playback and switch to new poster only if last one is in STOPPED state or if we have the default poster/random library poster.

**Comment by bdgarmon** [comment]
Thank you for fixing the bug. 

I've had a chance to think through this a bit more and my use case is this: I have a TV hanging on the wall outside my home theater. Anyone walking by or walking into the home theater should be able to see what is currently playing in the theater.  If nothing is playing in the theater, I would like the display to cycle through other posters. Randomly scrolling through other posters or showing what others are watching is a neat idea, but in my case I'd really like to say Priority 1 - if movie is playing on device X (which is the theater playback) then show it and only show it. When device X is not playing a movie, shuffle through others, and if no one is playing anything at all randomly shuffle.

**Comment by sahara101** [comment]
I can also add device priority, and last active of the priority is not active. I am working rn on the screensaver mode. Bear with me 😂

**Comment by sahara101** [comment]
Plan: 

- pick an option: default poster/screensaver
- all movies shuffle when not playing - pick between 1 min and 1h
- define a priority mechanism - pick between priority - last active - random

**Comment by sahara101** [comment]
It is admin defined. You can pick between several options. 

![image](https://github.com/user-attachments/assets/464b67ba-04c9-4d42-a25b-c94274fae5ba)

**Comment by bdgarmon** [comment]
I finally managed to get only a single person watching Plex and it was the local Apple TV on the LAN that is not showing any posters.  Here is what is recorded in the Docker logs while this Apple TV device is playing a movie: 

INFO:utils.cache_manager:Found 3555 currently unwatched movies
INFO:utils.cache_manager:Have 3555 cached unwatched movies
INFO:utils.cache_manager:No changes detected
INFO:utils.cache_manager:Processing library: Classic Films
INFO:utils.cache_manager:Processing library: Horror
INFO:utils.cache_manager:Processing library: Kids Movies
INFO:utils.cache_manager:Processing library: Movies
INFO:utils.cache_manager:Successfully cached 3884 total Plex movies
Client connected to poster namespace
server=192.168.11.216:4000//socket.io/ client=192.168.11.192:57873 socket shutdown error: [Errno 9] Bad file descriptorClient disconnected from poster namespace
DEBUG:utils.poster_view:Poster route called
DEBUG:utils.poster_view:Custom text from settings: ''
INFO:utils.default_poster_manager:Returning default poster
DEBUG:utils.poster_view:Current poster: /static/images/default_poster.png
DEBUG:utils.poster_view:Rendering default poster with custom text
Client connected to poster namespace

I'm not the best when it comes to troubleshooting Containers so if there' something more specific I can provide to help troubleshoot let me know.

**Comment by sahara101** [comment]
I don’t see the auth user info. Is the plex user selected in authorized ones?

**Comment by sahara101** [comment]
I saw I wrote above the other way around. Currently, posters are shown as the first active detected stream, not the last. Once you stop the first one, a new one will be shown for an active/next active stream.

Either way, I finished setting the screensaver mode and I am now thinking about how to do the priority. Does your home cinema use more than one user? Because if not, I could just slap a if user X is playing, always show that user, no matter if other plays started before from other users. 

Device priority is hard because I do not store all the data for them. 

Example: 

- you start the movie from movie-roulette. The network is scanned for a player capable of receiving play commands (plex for appletv, for lg, htpc etc). Movie starts, posters starts if user is authorized. There is nothing persistantly stored about the device. 
- you start the play outside of movie-roulette. The poster manager detects the play, shows the poster if user is authorized no matter from what device it comes from. Again, nothing about the device is persistantly stored. 


If there is an AppleTV/LG TV configured for the power feature, then yes, data about the device is persistently stored. In that case, it could be used in a poster priority mechanism.

**Comment by bdgarmon** [comment]
Home Cinema only has 1 user.

**Comment by sahara101** [comment]
Perfect. Doing all sorts of tests now and when I am pretty confident I will release it.

**Comment by sahara101** [comment]
I have released v3.3. Please test the new poster implementation. 

PS: I do not have any external monitors for portrait, I would appreciate a photo of yours to see how it looks like :D

**Comment by sahara101** [comment]
Did you test?

**Comment by bdgarmon** [comment]
I have updated to 3.3. The new poster features are working well but still having a few random issues related to playback. 

None of my local AppleTV devices are displaying "Now Playing" posters though the users on them are configured as users of the posters feature. I have not "registered" the local Apple TV devices on my network with this app so maybe that's part of the problem. I'll try that later today and see if that works. 

I've got a contractor coming out at the end of the week to mount the TV on the wall and run the wires through the walls so I can send some photos once that is cleaned up.

**Comment by bdgarmon** [comment]
Update on behavior: 

If no one is watching Plex, the screenshot below is what shows up in the movie poster app. I assume this is showing the "Stopped" because it's referencing the home theater user who is not watching anything, it's just a bit weird seeing the Stopped message displayed instead of the previous behavior where the entire upper menu was blank.  

Manually refreshing the webpage triggers a random poster to replace the image, or waiting the timeframe defined in the app for shuffle does shuffle to a random poster as well. 



<img width="840" alt="Image" src="https://github.com/user-attachments/assets/ff3b1f33-56be-40ce-8dae-37f1d0db5855" />

Would it be possible to change the default order so that the poster always starts with a random poster (Unless something is actively playing anywhere), then as soon as the priority user starts playing something it replaces whatever is being displayed?

**Comment by sahara101** [comment]
This happens while or directly after a movie was playing, right? I fixed the bug yesterday but did not release yet. 
Actually, that bug would show the entire default poster and not the top part...
Can you delete your config file and recreate it? I feel there is an issue between the old and new versions.

**Comment by bdgarmon** [comment]
Apologies, when I say I updated.... I'm using containers so I deleted the previous container running the old version and created a new container running version 3.3 so it would effectively be a fresh install not an update.

**Comment by sahara101** [comment]
The persistent storage is not lost on upgrades. The configuration file is in the persistent storage.

**Comment by sahara101** [comment]
Please update to v3.3.2 and redo the config. Delete the files in the ./movie_roulette_data folder or wherever you are saving it.

**Comment by bdgarmon** [comment]
Started from scratch with v3.3.2. At the moment no one is watching anything so upon first launch it defaulted to this screen which fixed the status bar. Thank you. 

Note this image is from the 50 inch TV I'm using, Chrome Browser in full screen mode. 

![Image](https://github.com/user-attachments/assets/aaccbf8c-a2db-4cd7-9e21-dcf025b9ab5d)

**Comment by sahara101** [comment]
Nice! When you have time can you also share a picture with a random movie and one when a movie is playing? I ask cause I don’t have a monitor to be able to properly test vertical. In case some tweaks are needed. 😁

**Comment by bdgarmon** [comment]
A user started playing a movie which fills the black space at the top and bottom of the border nicely. 

![Image](https://github.com/user-attachments/assets/5db4a3e8-7d88-41c4-87e3-0a5fb025a7e0)

The challenge I continue to face is that remote users viewing a movie always shows up properly on this app but devices on my local network are not. Within my home network I do use vLANS so I'm sorting through if this is part of the problem I'm seeing. I'll continue experimenting with this over the next day or two to see if I can make some headway.

**Comment by sahara101** [comment]
Most definitely a network issue. Try within the same vlan. 

PS: I found a small issue again which I thought I solved…I will try to solve in the next days.

**Comment by bdgarmon** [comment]
The local playback issue was a firewall rule so that is resolved, but it has revealed a new problem: 

Within MovieRoulette settings I've selected every Plex user as a Plex Poster Users. I pick a device, pick a user, start playing content and the Poster is updated to reflect whoever came in first. Rotation between users works in that when user A stops playing it swaps to the next device playing content, in what to me appears to be first in last out order. Which is great.  But if I choose my Plex account as the user and start watching anything on any device, MovieRoulette thinks nothing is playing. 

I have set my user account in MovieRoulette to be the preferred user with the setting "Preferred User Takes Priority" but even when no other user is playing content, nothing is displayed for a poster when I play content. 

Why would my account be treated any different from the other accounts that are working fine, other than the fact that my account is the server Plex admin account?

**Comment by sahara101** [comment]
What do the docker logs say? Works fine for me:

INFO:utils.plex_service:Could not determine username for client
INFO:utils.playback_monitor:Single authorized playback from xxx, allowing display
INFO:utils.playback_monitor:New movie or missing state file detected, updating poster: Agent Recon (plex)
INFO:utils.playback_monitor:Single authorized playback from xxx, allowing display
INFO:utils.poster_view:Authorized plex user xxx - updating poster


And when more plays at the same time, starting with an unauthorized user:

INFO:utils.playback_monitor:Unauthorized plex playback by user yyy
Then I start a movie

INFO:utils.playback_monitor:Single authorized playback from xxx, allowing display
INFO:utils.playback_monitor:New movie or missing state file detected, updating poster: Bruce Lee: The Man and the Legend (plex)
INFO:utils.playback_monitor:Single authorized playback from xxx, allowing display
INFO:utils.poster_view:Authorized plex user xxx - updating poster
INFO:utils.default_poster_manager:Handling playback state change: PLAYING
INFO:utils.default_poster_manager:Movie PLAYING - showing movie poster
INFO:utils.default_poster_manager:Stopping screensaver
INFO:utils.default_poster_manager:Maintaining current movie: Bruce Lee: The Man and the Legend
INFO:utils.playback_monitor:Single authorized playback from xxx, allowing display

I stop my play and then the unauthorized resumes in log, without poster update. 

INFO:utils.playback_monitor:Unauthorized plex playback by user yyy

**Comment by bdgarmon** [comment]
Whenever it's my account I see: 

NFO:utils.playback_monitor:Unauthorized plex playback by user vortex0007

Anyone else I see for example: 

INFO:utils.playback_monitor:Single authorized playback from cherishm, allowing display
INFO:utils.playback_monitor:New movie or missing state file detected, updating poster: Heavy Metal (plex)
INFO:utils.playback_monitor:Single authorized playback from cherishm, allowing display
INFO:utils.poster_view:Authorized plex user cherishm - updating poster

**Comment by sahara101** [comment]
SO all combinations are working fine on my end. Also more authorized users and preferred user mode, it will always override. 

According to the logs your user is not authorized. Can you show me a screenshot of the Poster Settings part?

**Comment by bdgarmon** [comment]
![Image](https://github.com/user-attachments/assets/d37ddc37-e2aa-47a7-8219-cf2795f09028)

**Comment by sahara101** [comment]
Ahh. You use the full name and the app does not consider this! I will come up with a fix.

**Comment by bdgarmon** [comment]
If it helps, I use the "Plex Home" feature. Plex Settings > Plex Home where my account is the Home Admin and I've added local family members. When any device in the house launches Plex it prompts for which Plex Home user is connecting and this is where I pick my account. I see no options to configure Full Name vs User name, it just automatically selected my Full Name with username in lower case beneath it and marked my account as the Home Admin.

**Comment by sahara101** [comment]
It is here. 

![Image](https://github.com/user-attachments/assets/0c738d2b-2863-48d4-8d79-5b73d4753942)

But nonetheless it should work with both. I just never used the full name option until today 😁

**Comment by sahara101** [comment]
OK, please try v3.3.3. Must work now. I just hope I did not break anything else xD

**Comment by sahara101** [comment]
OK, please try v3.3.3. Must work now. I just hope I did not break anything else xD

**Comment by sahara101** [comment]
OK, please try v3.3.3. Must work now. I just hope I did not break anything else xD

**Comment by sahara101** [comment]
OK, please try v3.3.3. Must work now. I just hope I did not break anything else xD

**Comment by bdgarmon** [comment]
I am sad to write that I'm seeing no change in behavior for my account after starting over with 3.3.3. The logs continue to record:

INFO:utils.playback_monitor:Unauthorized plex playback by user vortex0007
INFO:utils.playback_monitor:Unauthorized plex playback by user vortex0007
INFO:utils.playback_monitor:Unauthorized plex playback by user vortex0007

I've replicated this behavior on Apple TV 4K , Shield TV Pro, Plex app for macOS, and I'm setting up a new Roku to see if it's happening there as well but given that it's following me from device to device something else is broken. 

Does it matter that my account is the only account that owns a Plex pass?

**Comment by sahara101** [comment]
It does not. Mine is also the same. Can you post a screenshot as the one I made above with the user? 
Since it is mapping now fine, I cannot understand why it does not work for you yet.

**Comment by sahara101** [comment]
Thanks for the support! I changed so that it only checks for the username so that there won’t be any more issue with this. I just want to add one more fix to the poster change logic but it is now very late and will not manage today anymore.

**Comment by sahara101** [comment]
OOOK so let's try this again. Please update to v3.3.4. Also please reselect your preferred user in settings (it will be now the username displayed and not the plex user title).

**Comment by bdgarmon** [comment]
You fixed it!!!!! Horray!!!! THANK YOU!!!!

**Comment by sahara101** [comment]
I am sooo happy! Enjoy!
